# Generated by Django 2.2.3 on 2020-02-16 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MappingUserinfoDeviceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AppModel_userinfo_device_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_id', models.CharField(max_length=200, verbose_name='报警ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='联网单位')),
                ('device_sn', models.CharField(max_length=200, verbose_name='设备编码')),
                ('alarm_time', models.CharField(max_length=200, verbose_name='报警时间')),
                ('alarm_status', models.CharField(max_length=200, verbose_name='状态')),
                ('alarm_desc', models.CharField(max_length=200, verbose_name='报警详情')),
                ('alarm_handling', models.CharField(choices=[('0', '真实警情-小型'), ('1', '真实警情-大型'), ('2', '真实警情-大型（不启预案）'), ('3', '真实故障'), ('4', '人为误报')], max_length=200, verbose_name='警情处理')),
            ],
            options={
                'verbose_name': '报警中心',
                'verbose_name_plural': '报警中心',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(verbose_name='标签')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='AppModel.Category', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': 'categories',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=200, verbose_name='联网单位ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='单位全称')),
                ('company_address', models.CharField(max_length=200, verbose_name='单位地址')),
                ('latitude', models.CharField(max_length=200, verbose_name='经纬度')),
                ('detectors_number', models.CharField(max_length=200, verbose_name='探测器数量')),
                ('fire_brigade', models.CharField(max_length=200, verbose_name='所属消防队')),
                ('fire_number', models.CharField(max_length=200, verbose_name='消防队电话')),
                ('responsible_person', models.CharField(max_length=200, verbose_name='安全责任人')),
                ('responsible_number', models.CharField(max_length=200, verbose_name='责任人电话')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppModel.Category', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '联网单位',
                'verbose_name_plural': '联网单位',
            },
        ),
        migrations.CreateModel(
            name='Dangerrectification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_image', models.ImageField(blank=True, null=True, upload_to='danger_image', verbose_name='隐患图片')),
                ('danger_level', models.CharField(choices=[('0', '一般隐患'), ('1', '较大隐患'), ('2', '重大隐患'), ('3', '特别重大隐患')], max_length=200, verbose_name='隐患级别')),
                ('danger_type', models.CharField(choices=[('0', '消防管理'), ('1', '消防组织'), ('2', '人员设备'), ('3', '生产设备')], max_length=200, verbose_name='隐患类型')),
                ('danger_create_user', models.CharField(max_length=200, verbose_name='创建者')),
                ('danger_floor_level', models.CharField(max_length=200, verbose_name='楼层')),
                ('danger_address_detail', models.CharField(max_length=200, verbose_name='具体位置')),
                ('danger_status', models.CharField(choices=[('0', '待整改'), ('1', '整改中'), ('2', '整改完毕'), ('3', '驳回')], max_length=200, verbose_name='隐患状态')),
                ('danger_create_time', models.DateField(default=datetime.date.today, verbose_name='创建时间')),
                ('danger_desc', models.TextField(verbose_name='隐患描述')),
                ('if_reject', models.CharField(choices=[('0', '是'), ('1', '否')], max_length=200, verbose_name='是否驳回')),
            ],
            options={
                'verbose_name': '隐患整改',
                'verbose_name_plural': '隐患整改',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='设备ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('device_sn', models.CharField(max_length=200, verbose_name='设备编号')),
                ('tenantId', models.CharField(max_length=200, verbose_name='租户Id')),
                ('productId', models.CharField(max_length=200, verbose_name='产品Id')),
                ('imei', models.CharField(max_length=200, verbose_name='IMEI号')),
                ('deviceStatus', models.CharField(max_length=200, verbose_name='设备状态')),
                ('autoObserver', models.CharField(max_length=200, verbose_name='是否订阅')),
                ('createTime', models.CharField(max_length=200, verbose_name='创建时间')),
                ('createBy', models.CharField(max_length=200, verbose_name='创建者')),
                ('netStatus', models.CharField(max_length=200, verbose_name='信号强度')),
                ('onlineAt', models.CharField(max_length=200, verbose_name='最后上线时间')),
                ('offlineAt', models.CharField(max_length=200, verbose_name='最后离线时间')),
                ('isOnline', models.CharField(max_length=200, verbose_name='是否已上线')),
                ('deviceVoltageStatus', models.CharField(max_length=200, verbose_name='设备电压状态')),
                ('lastUploadTime', models.CharField(max_length=200, verbose_name='上报时间')),
                ('companyinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppModel.CompanyInfo', verbose_name='联网单位')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.CreateModel(
            name='InstitutionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=200, verbose_name='组织机构ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('superior_department', models.CharField(max_length=200, verbose_name='上级部门')),
                ('create_time', models.CharField(max_length=200, verbose_name='创建时间')),
                ('create_user', models.CharField(max_length=200, verbose_name='创建者')),
                ('connact_number', models.CharField(max_length=200, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
            },
        ),
        migrations.CreateModel(
            name='OnlineDeviceInfo',
            fields=[
                ('deviceinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppModel.DeviceInfo')),
            ],
            options={
                'verbose_name': '上线设备信息',
                'verbose_name_plural': '上线设备信息',
            },
            bases=('AppModel.deviceinfo',),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('login_name', models.CharField(max_length=200, verbose_name='用户名')),
                ('username', models.CharField(max_length=200, verbose_name='姓名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('user_permission', models.CharField(max_length=200, verbose_name='权限')),
                ('phone_number', models.CharField(max_length=200, verbose_name='手机号')),
                ('create_time', models.CharField(max_length=200, verbose_name='创建时间')),
                ('description', models.CharField(max_length=200, verbose_name='用户描述')),
                ('user_sex', models.CharField(max_length=200, verbose_name='性别')),
                ('user_age', models.CharField(max_length=200, verbose_name='年龄')),
                ('device_name', models.ManyToManyField(blank=True, null=True, to='AppModel.DeviceInfo', verbose_name='设备名字')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='单位名称')),
                ('createtime', models.CharField(max_length=200, verbose_name='创建时间')),
                ('createuser', models.CharField(max_length=200, verbose_name='创建者')),
                ('connected_number', models.CharField(max_length=200, verbose_name='联系电话')),
                ('slug', models.SlugField(verbose_name='标签')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppModel.Category', verbose_name='上级部门')),
            ],
        ),
        migrations.CreateModel(
            name='Patrolscheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=200, verbose_name='巡检名称')),
                ('scheme_frequency', models.CharField(choices=[('0', '一天'), ('1', '一周'), ('2', '一月')], max_length=200, verbose_name='巡检频率')),
                ('scheme_start_time', models.DateField(default=datetime.date.today, verbose_name='开始时间')),
                ('scheme_end_time', models.DateField(default=datetime.date.today, verbose_name='结束时间')),
                ('scheme_desc', models.CharField(max_length=200, verbose_name='巡检描述')),
                ('scheme_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppModel.DeviceInfo', verbose_name='巡检设备')),
            ],
            options={
                'verbose_name': '巡检计划',
                'verbose_name_plural': '巡检计划',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_desc', models.TextField(verbose_name='问题描述')),
                ('create_time', models.DateField(default=datetime.date.today, verbose_name='问题上报时间')),
                ('progress', models.CharField(choices=[('0', '保养中'), ('1', '已完成')], max_length=200, verbose_name='解决状态')),
                ('problem_type', models.CharField(choices=[('0', '电池更换'), ('1', '设备损坏'), ('2', '信号不良'), ('3', '人为损坏')], max_length=200, verbose_name='问题类型')),
                ('problem_images', models.FileField(upload_to='maintenance_images', verbose_name='图片')),
                ('deviceinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppModel.DeviceInfo', verbose_name='问题设备')),
                ('userinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppModel.UserInfo', verbose_name='维修人员')),
            ],
        ),
    ]
