# Generated by Django 2.2.3 on 2020-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('login_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('user_permission', models.CharField(max_length=200)),
                ('create_time', models.CharField(max_length=200)),
                ('is_deleted', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('class_id', models.CharField(max_length=200)),
            ],
        ),
    ]
