# Generated by Django 2.2.3 on 2020-01-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200, verbose_name='设备ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('device_address', models.CharField(max_length=200, verbose_name='部件地址')),
                ('device_address_detail', models.CharField(max_length=200, verbose_name='具体位置')),
                ('device_status', models.CharField(max_length=200, verbose_name='设备状态')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='class_id',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='description',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_deleted',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='login_name',
            field=models.CharField(max_length=200, verbose_name='登录名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=200, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_permission',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
    ]
