# Generated by Django 2.2.3 on 2020-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default=1, max_length=200, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_age',
            field=models.CharField(default=1, max_length=200, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_sex',
            field=models.CharField(default=1, max_length=200, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='deviceStatus',
            field=models.CharField(max_length=200, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='offlineAt',
            field=models.CharField(max_length=200, verbose_name='最后离线时间'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='onlineAt',
            field=models.CharField(max_length=200, verbose_name='最后上线时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.CharField(max_length=200, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='description',
            field=models.CharField(max_length=200, verbose_name='用户描述'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='login_name',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_permission',
            field=models.CharField(max_length=200, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
    ]
