# Generated by Django 2.2.3 on 2020-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0002_auto_20200130_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=200, verbose_name='组织机构ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='单位全称')),
                ('established_time', models.CharField(max_length=200, verbose_name='成立时间')),
                ('company_address', models.CharField(max_length=200, verbose_name='单位全称')),
                ('post_number', models.CharField(max_length=200, verbose_name='邮政编码')),
                ('floor_area', models.CharField(max_length=200, verbose_name='占地面积')),
                ('fire_rating', models.CharField(max_length=200, verbose_name='防火等级')),
                ('detectors_number', models.CharField(max_length=200, verbose_name='探测器数量')),
                ('fire_brigade', models.CharField(max_length=200, verbose_name='所属消防队')),
                ('region', models.CharField(max_length=200, verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
            },
        ),
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'verbose_name': '设备信息', 'verbose_name_plural': '设备信息'},
        ),
    ]
