# Generated by Django 2.2.3 on 2020-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0003_auto_20200130_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioninfo',
            name='fire_rating',
            field=models.CharField(choices=[('0', '一级'), ('1', '二级')], max_length=200, verbose_name='防火等级'),
        ),
    ]
